(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={events:[],users:[],user:'',authUser:null,profile:null,role:'',view:'dashboard',dashDate:new Date(),calDate:new Date(),eventSubscriptionStarted:false,userUnsubscribe:null};
const statusClass=s=>'status-'+s.toLowerCase().replaceAll(' ','-');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>d?new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
const fmtDateTime=d=>d?new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(d)):'';
const monthName=d=>new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric'}).format(d);
const slug=s=>String(s||'archivo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_|_$/g,'');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(id){$('#'+id).classList.add('open')} function closeModal(id){$('#'+id).classList.remove('open')}
function combine(date,time){return date&&time?new Date(`${date}T${time}:00`):null}
function durationMinutes(e){const a=combine(e.startDate,e.presentationTime),b=combine(e.endDate,e.returnTime);return a&&b?Math.max(0,Math.round((b-a)/60000)):0}
function durationText(m){return `${Math.floor(m/60)} h ${String(m%60).padStart(2,'0')} min`}
function overlap(a,b){const as=combine(a.startDate,a.presentationTime),ae=combine(a.endDate,a.returnTime),bs=combine(b.startDate,b.presentationTime),be=combine(b.endDate,b.returnTime);return as&&ae&&bs&&be&&as<be&&bs<ae}
function activeEvents(){return state.events.filter(e=>!e.deleted)} function deletedEvents(){return state.events.filter(e=>e.deleted)}
function historyEntry(action,details=''){return{action,details,user:state.user,userUid:state.authUser?.uid||'',at:new Date().toISOString()}}
function isAdmin(){return state.role==='admin'} function canEdit(){return state.role==='admin'||state.role==='user'} function isReadonly(){return state.role==='readonly'}

function setup(){
  $('#loginForm').addEventListener('submit',login);
  $('#forgotPasswordBtn').onclick=forgotPassword;
  $('#logoutBtn').onclick=()=>AuthStore.logout();
  $$('#mainNav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
  $('#newEventBtn').onclick=()=>{if(canEdit())openEventForm();else toast('Tu perfil es de solo lectura')};
  $$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
  $('#eventType').onchange=toggleConditional; $('#eventStatus').onchange=toggleConditional;
  ['startDate','endDate','presentationTime','returnTime'].forEach(id=>$('#'+id).addEventListener('input',updateDuration));
  $('#addTeamBtn').onclick=()=>addTeamRow(); $('#addVehicleBtn').onclick=()=>addVehicleRow(); $('#eventForm').onsubmit=saveEvent;
  $('#dashPrev').onclick=()=>{state.dashDate.setMonth(state.dashDate.getMonth()-1);renderDashboard()}; $('#dashNext').onclick=()=>{state.dashDate.setMonth(state.dashDate.getMonth()+1);renderDashboard()};
  $('#calPrev').onclick=()=>{state.calDate.setMonth(state.calDate.getMonth()-1);renderCalendar()}; $('#calNext').onclick=()=>{state.calDate.setMonth(state.calDate.getMonth()+1);renderCalendar()};
  ['filterText','filterFrom','filterTo','filterType','filterStatus','filterPerson','filterVehicle'].forEach(id=>$('#'+id).addEventListener('input',renderEventsTable));
  $('#clearFiltersBtn').onclick=()=>{['filterText','filterFrom','filterTo','filterType','filterStatus','filterPerson','filterVehicle'].forEach(id=>$('#'+id).value='');renderEventsTable()};
  $('#previewReportBtn').onclick=renderReport; $('#reportPdfBtn').onclick=()=>printReport(); $('#reportCsvBtn').onclick=()=>exportReport('csv'); $('#reportExcelBtn').onclick=()=>exportReport('xls'); $('#backupBtn').onclick=backupJson; $('#importBackup').onchange=importJson;
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(console.warn);
  AuthStore.watch(handleAuthState);
}
async function login(event){
  event.preventDefault();
  const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value,remember=$('#rememberSession').checked;
  const error=$('#loginError');error.classList.add('hidden');
  try{await AuthStore.login(email,password,remember)}catch(e){error.textContent=e.userMessage||e.message;error.classList.remove('hidden')}
}
async function forgotPassword(){
  const email=$('#loginEmail').value.trim();
  try{await AuthStore.resetPassword(email);toast('Correo de recuperación enviado')}catch(e){const box=$('#loginError');box.textContent=e.message||'No fue posible enviar el correo';box.classList.remove('hidden')}
}
function handleAuthState(user,profile,error){
  if(!user){state.authUser=null;state.profile=null;state.role='';state.user='';$('#appShell').classList.add('hidden');$('#loginScreen').classList.remove('hidden');return}
  if(error||!profile){AuthStore.logout();const box=$('#loginError');box.textContent='La cuenta existe, pero no tiene un perfil autorizado en Firestore.';box.classList.remove('hidden');return}
  if(profile.active!==true){AuthStore.logout();const box=$('#loginError');box.textContent='Esta cuenta está desactivada. Contacta a un administrador.';box.classList.remove('hidden');return}
  state.authUser=user;state.profile=profile;state.role=profile.role||'readonly';state.user=profile.fullName||user.email;
  $('#activeUser').textContent=state.user;$('#activeRole').textContent=roleLabel(state.role);$('#loginScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');applyPermissions();
  if(!state.eventSubscriptionStarted){state.eventSubscriptionStarted=true;EventStore.subscribe(events=>{state.events=events;renderAll()},err=>{console.error(err);toast('No fue posible conectar con Firestore')})}
  if(isAdmin()&&!state.userUnsubscribe){state.userUnsubscribe=UserStore.subscribe(users=>{state.users=users;renderUsers()},err=>console.error(err))}
  setView('dashboard');
}
function roleLabel(role){return({admin:'Administrador',user:'Usuario',readonly:'Solo lectura'})[role]||role}
function applyPermissions(){
  $$('.admin-only').forEach(el=>el.classList.toggle('hidden',!isAdmin()));
  $('#newEventBtn').classList.toggle('hidden',!canEdit());
  $('#importBackup').closest('label').classList.toggle('hidden',!isAdmin());
  if(!isAdmin()&&state.view==='users')setView('dashboard');
  if(!isAdmin()&&state.view==='trash')setView('dashboard');
  renderAll();
}
function setView(v){state.view=v;$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$$('#mainNav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const titles={dashboard:['Dashboard','Resumen operativo del mes actual'],calendar:['Calendario','Vista mensual de coberturas'],events:['Eventos','Administración y filtros'],reports:['Informes','Consolidación y exportaciones'],users:['Usuarios','Roles y acceso'],trash:['Papelera','Eventos eliminados']};$('#pageTitle').textContent=titles[v][0];$('#pageSubtitle').textContent=titles[v][1];$('#newEventBtn').style.display=v==='trash'?'none':'';renderAll()}
function renderAll(){renderDashboard();renderCalendar();renderEventsTable();if(isAdmin())renderTrash();if(isAdmin())renderUsers();if(state.view==='reports')renderReport()}

function monthlyEvents(date){const y=date.getFullYear(),m=date.getMonth();return activeEvents().filter(e=>{const d=new Date(e.startDate+'T12:00:00');return d.getFullYear()===y&&d.getMonth()===m})}
function eventConflicts(e){const result=[];for(const other of activeEvents()){if(other.id===e.id||!overlap(e,other))continue;const people=(e.team||[]).map(x=>x.name.trim().toLowerCase()).filter(Boolean);const op=(other.team||[]).map(x=>x.name.trim().toLowerCase());const vehicles=(e.vehicles||[]).map(v=>(v.type==='Otro'?v.other:v.type).toLowerCase());const ov=(other.vehicles||[]).map(v=>(v.type==='Otro'?v.other:v.type).toLowerCase());if(people.some(p=>op.includes(p)))result.push(`Funcionario duplicado con “${other.name}”`);if(vehicles.some(v=>v&&ov.includes(v)))result.push(`Móvil duplicado con “${other.name}”`)}return [...new Set(result)]}
function alertsFor(e){const a=[];const start=new Date(e.startDate+'T00:00:00'),days=(start-new Date())/86400000;if(days>=0&&days<=5)a.push('Evento dentro de los próximos cinco días');if(days>=0&&days<=5&&e.status==='Programado')a.push('Evento próximo sin confirmar');if(!(e.team||[]).length)a.push('Sin equipo asignado');if(!(e.vehicles||[]).length)a.push('Sin móvil asignado');a.push(...eventConflicts(e));return a}
function renderDashboard(){const ev=monthlyEvents(state.dashDate);$('#dashMonth').textContent=monthName(state.dashDate);const upcoming=activeEvents().filter(e=>new Date(e.startDate+'T23:59:59')>=new Date()).sort((a,b)=>a.startDate.localeCompare(b.startDate)).slice(0,8);const metrics=[['Total del mes',ev.length],['Próximos',upcoming.length],['Confirmados',ev.filter(e=>e.status==='Confirmado').length],['Finalizados',ev.filter(e=>e.status==='Finalizado').length],['Cancelados',ev.filter(e=>e.status==='Cancelado').length],['Horas de cobertura',(ev.reduce((s,e)=>s+durationMinutes(e),0)/60).toFixed(1)]];$('#metricCards').innerHTML=metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
$('#upcomingList').innerHTML=upcoming.length?upcoming.map(e=>`<div class="list-item"><strong>${esc(e.name)}</strong><span>${fmtDate(e.startDate)} · ${esc(e.location)} · ${esc((e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join(', ')||'Sin móvil')}</span><span class="badge ${statusClass(e.status)}">${esc(e.status)}</span></div>`).join(''):'<div class="empty">Sin próximos eventos.</div>';
const alerts=activeEvents().flatMap(e=>alertsFor(e).map(a=>({e,a}))).slice(0,12);$('#alertsList').innerHTML=alerts.length?alerts.map(x=>`<div class="alert"><strong>${esc(x.e.name)}</strong><div>${esc(x.a)}</div></div>`).join(''):'<div class="empty">Sin alertas activas.</div>';
const people={};ev.forEach(e=>(e.team||[]).forEach(p=>people[p.name]=(people[p.name]||0)+1));$('#participationList').innerHTML=Object.entries(people).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="list-item"><strong>${esc(n)}</strong><span>${c} evento(s)</span></div>`).join('')||'<div class="empty">Sin participación registrada.</div>';
const types=['Deportivo','Académico','Otro'];$('#typeList').innerHTML=types.map(t=>`<div class="list-item"><strong>${t}</strong><span>${ev.filter(e=>e.type===t).length} evento(s)</span></div>`).join('')}

function renderCalendar(){const d=state.calDate,y=d.getFullYear(),m=d.getMonth();$('#calMonth').textContent=monthName(d);const first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset);let html='';for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const iso=day.toISOString().slice(0,10);const ev=activeEvents().filter(e=>iso>=e.startDate&&iso<=e.endDate);html+=`<div class="day ${day.getMonth()!==m?'muted':''}"><div class="day-number">${day.getDate()}</div>${ev.slice(0,5).map(e=>`<div class="cal-event ${e.status}" data-event="${e.id}" title="${esc(e.name)}">${esc(e.name)}</div>`).join('')}</div>`}$('#calendarGrid').innerHTML=html;$$('[data-event]').forEach(x=>x.onclick=()=>showDetail(x.dataset.event))}
function filteredEvents(prefix='filter'){const get=id=>$('#'+prefix+id).value.trim().toLowerCase();const text=get('Text'),from=get('From'),to=get('To'),type=$('#'+prefix+'Type').value,status=$('#'+prefix+'Status').value,person=get('Person'),vehicle=get('Vehicle');return activeEvents().filter(e=>{const blob=[e.name,e.location,e.type,e.otherType,e.status,(e.team||[]).map(p=>p.name+' '+p.role).join(' '),(e.vehicles||[]).map(v=>v.type+' '+v.other).join(' ')].join(' ').toLowerCase();return(!text||blob.includes(text))&&(!from||e.endDate>=from)&&(!to||e.startDate<=to)&&(!type||e.type===type)&&(!status||e.status===status)&&(!person||(e.team||[]).some(p=>(p.name+' '+p.role).toLowerCase().includes(person)))&&(!vehicle||(e.vehicles||[]).some(v=>(v.type+' '+v.other).toLowerCase().includes(vehicle)))})}
function renderEventsTable(){const ev=filteredEvents();$('#eventsTable').innerHTML=ev.length?ev.sort((a,b)=>a.startDate.localeCompare(b.startDate)).map(e=>`<tr><td><strong>${esc(e.name)}</strong></td><td>${fmtDate(e.startDate)}${e.endDate!==e.startDate?' al '+fmtDate(e.endDate):''}</td><td>${esc(e.location)}</td><td><span class="badge ${statusClass(e.status)}">${esc(e.status)}</span></td><td>${esc((e.team||[]).map(p=>p.name).join(', ')||'Sin equipo')}</td><td>${esc((e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join(', ')||'Sin móvil')}</td><td>${durationText(durationMinutes(e))}</td><td><div class="actions"><button class="btn" data-view-event="${e.id}">Ver</button>${canEdit()?`<button class="btn" data-edit-event="${e.id}">Editar</button>`:''}<button class="btn" data-wa="${e.id}">WhatsApp</button><button class="btn" data-pdf="${e.id}">PDF</button>${canEdit()?`<button class="btn danger" data-trash="${e.id}">Eliminar</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No hay eventos para los filtros seleccionados.</td></tr>';bindRowActions()}
function bindRowActions(){$$('[data-view-event]').forEach(b=>b.onclick=()=>showDetail(b.dataset.viewEvent));$$('[data-edit-event]').forEach(b=>b.onclick=()=>openEventForm(b.dataset.editEvent));$$('[data-wa]').forEach(b=>b.onclick=()=>openWhatsApp(b.dataset.wa));$$('[data-pdf]').forEach(b=>b.onclick=()=>printEvent(b.dataset.pdf));$$('[data-trash]').forEach(b=>b.onclick=()=>trashEvent(b.dataset.trash))}

function resetForm(){ $('#eventForm').reset();$('#eventId').value='';$('#eventStatus').value='Programado';$('#teamRows').innerHTML='';$('#vehicleRows').innerHTML='';addTeamRow();addVehicleRow();toggleConditional();updateDuration();$('#formWarnings').classList.add('hidden') }
function openEventForm(id){if(!canEdit()){toast('Tu perfil es de solo lectura');return}resetForm();const e=state.events.find(x=>x.id===id);$('#eventModalTitle').textContent=e?'Editar evento':'Nuevo evento';if(e){$('#eventId').value=e.id;$('#eventName').value=e.name||'';$('#eventType').value=e.type||'';$('#eventOtherType').value=e.otherType||'';$('#eventLocation').value=e.location||'';$('#startDate').value=e.startDate||'';$('#endDate').value=e.endDate||'';$('#eventStatus').value=e.status||'Programado';$('#cancelReason').value=e.cancelReason||'';$('#presentationTime').value=e.presentationTime||'';$('#arrivalTime').value=e.arrivalTime||'';$('#eventStartTime').value=e.eventStartTime||'';$('#eventEndTime').value=e.eventEndTime||'';$('#returnTime').value=e.returnTime||'';$('#eventNotes').value=e.notes||'';$('#teamRows').innerHTML='';(e.team||[]).forEach(addTeamRow);$('#vehicleRows').innerHTML='';(e.vehicles||[]).forEach(addVehicleRow)}toggleConditional();updateDuration();openModal('eventModal')}
function addTeamRow(p={}){const d=document.createElement('div');d.className='team-row';d.innerHTML=`<input class="team-name" placeholder="Nombre completo" value="${esc(p.name||'')}"><select class="team-role"><option>Enfermero/a</option><option>TENS</option><option>Conductor/a</option><option>Médico/a</option><option>Otro</option></select><select class="team-condition"><option>Interno</option><option>Externo</option></select><select class="team-participation"><option>Titular</option><option>Reemplazo</option></select><button type="button" class="remove-row">×</button>`;d.querySelector('.team-role').value=p.role||'Enfermero/a';d.querySelector('.team-condition').value=p.condition||'Interno';d.querySelector('.team-participation').value=p.participation||'Titular';d.querySelector('.remove-row').onclick=()=>d.remove();$('#teamRows').appendChild(d)}
function addVehicleRow(v={}){const d=document.createElement('div');d.className='vehicle-row';d.innerHTML=`<select class="vehicle-type"><option>M2</option><option>M4</option><option>M5</option><option>VIR</option><option>Otro</option></select><input class="vehicle-other" placeholder="Especificar si es Otro" value="${esc(v.other||'')}"><button type="button" class="remove-row">×</button>`;d.querySelector('.vehicle-type').value=v.type||'M5';d.querySelector('.remove-row').onclick=()=>d.remove();$('#vehicleRows').appendChild(d)}
function toggleConditional(){$('#otherTypeWrap').classList.toggle('hidden',$('#eventType').value!=='Otro');$('#cancelReasonWrap').classList.toggle('hidden',$('#eventStatus').value!=='Cancelado')}
function updateDuration(){const e={startDate:$('#startDate').value,endDate:$('#endDate').value,presentationTime:$('#presentationTime').value,returnTime:$('#returnTime').value};$('#durationDisplay').textContent=durationText(durationMinutes(e))}
function collectForm(){return{id:$('#eventId').value||undefined,name:$('#eventName').value.trim(),type:$('#eventType').value,otherType:$('#eventOtherType').value.trim(),location:$('#eventLocation').value.trim(),startDate:$('#startDate').value,endDate:$('#endDate').value,status:$('#eventStatus').value,cancelReason:$('#cancelReason').value.trim(),presentationTime:$('#presentationTime').value,arrivalTime:$('#arrivalTime').value,eventStartTime:$('#eventStartTime').value,eventEndTime:$('#eventEndTime').value,returnTime:$('#returnTime').value,notes:$('#eventNotes').value.trim(),team:$$('.team-row').map(r=>({name:r.querySelector('.team-name').value.trim(),role:r.querySelector('.team-role').value,condition:r.querySelector('.team-condition').value,participation:r.querySelector('.team-participation').value})).filter(p=>p.name),vehicles:$$('.vehicle-row').map(r=>({type:r.querySelector('.vehicle-type').value,other:r.querySelector('.vehicle-other').value.trim()})).filter(v=>v.type!=='Otro'||v.other)}}
async function saveEvent(ev){ev.preventDefault();if(!canEdit()){toast('No tienes permisos para modificar eventos');return}const data=collectForm();const errors=[];if(!data.name||!data.type||!data.location||!data.startDate||!data.endDate||!data.presentationTime||!data.returnTime)errors.push('Completa todos los campos obligatorios.');if(data.type==='Otro'&&!data.otherType)errors.push('Especifica el tipo de evento.');if(data.status==='Cancelado'&&!data.cancelReason)errors.push('Ingresa el motivo de cancelación.');if(data.endDate<data.startDate)errors.push('La fecha de término no puede ser anterior al inicio.');if(combine(data.endDate,data.returnTime)<=combine(data.startDate,data.presentationTime))errors.push('El regreso debe ser posterior a la presentación.');if(errors.length){showWarnings(errors);return}const old=state.events.find(x=>x.id===data.id);data.createdBy=old?.createdBy||state.user;data.createdAt=old?.createdAt||new Date().toISOString();data.updatedBy=state.user;data.deleted=old?.deleted||false;data.history=[...(old?.history||[]),historyEntry(old?'Evento modificado':'Evento creado')];const conflicts=eventConflicts(data);if(conflicts.length&&!confirm(`Se detectó un conflicto de horario:\n\n${conflicts.join('\n')}\n\n¿Desea guardar igualmente?`))return;try{await EventStore.save(data);closeModal('eventModal');toast('Evento guardado correctamente')}catch(e){console.error(e);toast('No fue posible guardar el evento')}}
function showWarnings(arr){const w=$('#formWarnings');w.innerHTML='<strong>Revisa lo siguiente:</strong><ul>'+arr.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>';w.classList.remove('hidden')}

function showDetail(id){const e=state.events.find(x=>x.id===id);if(!e)return;const team=(e.team||[]).map(p=>`<li>${esc(p.role)}: ${esc(p.name)} · ${esc(p.condition)} · ${esc(p.participation)} · ${durationText(durationMinutes(e))}</li>`).join('')||'<li>Sin equipo</li>';const hist=(e.history||[]).slice().reverse().map(h=>`<div class="history-item"><strong>${esc(h.action)}</strong> · ${esc(h.user)}<br>${fmtDateTime(h.at)} ${h.details?'· '+esc(h.details):''}</div>`).join('')||'<div class="empty">Sin historial.</div>';$('#detailContent').innerHTML=`<div class="detail-grid"><div><strong>Nombre</strong><p>${esc(e.name)}</p></div><div><strong>Tipo</strong><p>${esc(e.type==='Otro'?e.otherType:e.type)}</p></div><div><strong>Fecha</strong><p>${fmtDate(e.startDate)} al ${fmtDate(e.endDate)}</p></div><div><strong>Lugar</strong><p>${esc(e.location)}</p></div><div><strong>Estado</strong><p><span class="badge ${statusClass(e.status)}">${esc(e.status)}</span></p></div><div><strong>Duración</strong><p>${durationText(durationMinutes(e))}</p></div><div><strong>Horarios</strong><p>Presentación ${esc(e.presentationTime)} · Llegada ${esc(e.arrivalTime||'-')} · Inicio ${esc(e.eventStartTime||'-')} · Término ${esc(e.eventEndTime||'-')} · Regreso ${esc(e.returnTime)}</p></div><div><strong>Móviles</strong><p>${esc((e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join(', ')||'Sin móvil')}</p></div></div><h3>Equipo asistente</h3><ul>${team}</ul>${e.cancelReason?`<h3>Motivo de cancelación</h3><p>${esc(e.cancelReason)}</p>`:''}<h3>Observaciones</h3><p>${esc(e.notes||'Sin observaciones')}</p><h3>Trazabilidad</h3><p>Creado por ${esc(e.createdBy||'-')} el ${fmtDateTime(e.createdAt)}<br>Última modificación por ${esc(e.updatedBy||'-')} el ${fmtDateTime(e.updatedAt)}</p><h3>Historial</h3>${hist}`;openModal('detailModal')}
async function trashEvent(id){if(!canEdit()){toast('No tienes permisos para eliminar eventos');return}const reason=prompt('Motivo de eliminación:');if(reason===null)return;if(!reason.trim()){toast('Debes indicar un motivo');return}await EventStore.trash(id,{user:state.user,reason:reason.trim()});toast('Evento enviado a la papelera')}
function renderTrash(){if(!isAdmin())return;const ev=deletedEvents();$('#trashTable').innerHTML=ev.length?ev.map(e=>`<tr><td>${esc(e.name)}</td><td>${fmtDate(e.startDate)}</td><td>${fmtDateTime(e.deletedAt)}</td><td>${esc(e.deletedBy||'')}</td><td>${esc(e.deletionReason||'')}</td><td><div class="actions"><button class="btn" data-restore="${e.id}">Restaurar</button><button class="btn danger" data-delete="${e.id}">Eliminar definitivamente</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty">La papelera está vacía.</td></tr>';$$('[data-restore]').forEach(b=>b.onclick=()=>EventStore.restore(b.dataset.restore,state.user));$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Esta acción no se puede deshacer. ¿Eliminar definitivamente?'))await EventStore.remove(b.dataset.delete)})}
function renderUsers(){
  const table=$('#usersTable');if(!table||!isAdmin())return;
  table.innerHTML=state.users.length?state.users.map(u=>`<tr data-user-row="${u.uid}"><td><input class="user-name-input" value="${esc(u.fullName||'')}"></td><td>${esc(u.email||'')}</td><td><select class="user-role-select"><option value="admin">Administrador</option><option value="user">Usuario</option><option value="readonly">Solo lectura</option></select></td><td><label class="status-toggle"><input class="user-active" type="checkbox" ${u.active===true?'checked':''}> Activo</label></td><td><button class="btn user-save">Guardar</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No hay perfiles registrados.</td></tr>';
  $$('[data-user-row]').forEach(row=>{const u=state.users.find(x=>x.uid===row.dataset.userRow);row.querySelector('.user-role-select').value=u.role||'readonly';row.querySelector('.user-save').onclick=async()=>{if(u.uid===state.authUser.uid&&!row.querySelector('.user-active').checked){toast('No puedes desactivar tu propia cuenta');return}try{await UserStore.update(u.uid,{fullName:row.querySelector('.user-name-input').value,role:row.querySelector('.user-role-select').value,active:row.querySelector('.user-active').checked},state.user);toast('Usuario actualizado')}catch(e){console.error(e);toast('No fue posible actualizar el usuario')}}})
}

function whatsappText(e){return`Cobertura de evento – Rescate CUA\n\nEvento: ${e.name}\nTipo: ${e.type==='Otro'?e.otherType:e.type}\nFecha: ${fmtDate(e.startDate)}${e.endDate!==e.startDate?' al '+fmtDate(e.endDate):''}\nLugar: ${e.location}\nPresentación en clínica: ${e.presentationTime} horas\nLlegada al evento: ${e.arrivalTime||'-'} horas\nInicio: ${e.eventStartTime||'-'} horas\nTérmino: ${e.eventEndTime||'-'} horas\nLlegada estimada a clínica: ${e.returnTime} horas\n\nEquipo asistente:\n${(e.team||[]).map(p=>`• ${p.role}: ${p.name}`).join('\n')||'• Sin equipo asignado'}\n\nMóvil: ${(e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join(', ')||'Sin móvil'}\nEstado: ${e.status}`}
function openWhatsApp(id){const e=state.events.find(x=>x.id===id);window.open('https://wa.me/?text='+encodeURIComponent(whatsappText(e)),'_blank','noopener')}
function printHtml(title,body){const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Arial;padding:30px;color:#173247}h1{color:#0b5a91}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccd;padding:8px;text-align:left}@page{size:letter;margin:15mm}</style></head><body>${body}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
function printEvent(id){const e=state.events.find(x=>x.id===id);printHtml(e.name,`<h1>${esc(e.name)}</h1><p><b>Tipo:</b> ${esc(e.type==='Otro'?e.otherType:e.type)}<br><b>Fecha:</b> ${fmtDate(e.startDate)} al ${fmtDate(e.endDate)}<br><b>Lugar:</b> ${esc(e.location)}<br><b>Estado:</b> ${esc(e.status)}<br><b>Duración:</b> ${durationText(durationMinutes(e))}</p><h2>Equipo</h2><ul>${(e.team||[]).map(p=>`<li>${esc(p.role)} · ${esc(p.name)} · ${esc(p.condition)} · ${esc(p.participation)}</li>`).join('')}</ul><h2>Móviles</h2><p>${esc((e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join(', '))}</p><h2>Observaciones</h2><p>${esc(e.notes||'')}</p><p><small>Creado por ${esc(e.createdBy)} · Última modificación por ${esc(e.updatedBy)}</small></p>`)}

function reportEvents(){const get=id=>$('#report'+id).value.trim().toLowerCase();const from=get('From'),to=get('To'),type=$('#reportType').value,status=$('#reportStatus').value,person=get('Person'),vehicle=get('Vehicle');return activeEvents().filter(e=>(!from||e.endDate>=from)&&(!to||e.startDate<=to)&&(!type||e.type===type)&&(!status||e.status===status)&&(!person||(e.team||[]).some(p=>(p.name+' '+p.role).toLowerCase().includes(person)))&&(!vehicle||(e.vehicles||[]).some(v=>(v.type+' '+v.other).toLowerCase().includes(vehicle))))}
function reportHtml(ev){const hours=(ev.reduce((s,e)=>s+durationMinutes(e),0)/60).toFixed(1);const people={};ev.forEach(e=>(e.team||[]).forEach(p=>people[p.name]=(people[p.name]||0)+1));return`<h2>Informe consolidado de eventos</h2><div class="summary-grid"><div><b>Total</b><br>${ev.length}</div><div><b>Confirmados</b><br>${ev.filter(e=>e.status==='Confirmado').length}</div><div><b>Finalizados</b><br>${ev.filter(e=>e.status==='Finalizado').length}</div><div><b>Horas totales</b><br>${hours}</div></div><h3>Listado</h3><table><thead><tr><th>Evento</th><th>Fecha</th><th>Tipo</th><th>Estado</th><th>Equipo</th><th>Móviles</th><th>Horas</th></tr></thead><tbody>${ev.map(e=>`<tr><td>${esc(e.name)}</td><td>${fmtDate(e.startDate)}</td><td>${esc(e.type==='Otro'?e.otherType:e.type)}</td><td>${esc(e.status)}</td><td>${esc((e.team||[]).map(p=>p.name).join(', '))}</td><td>${esc((e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join(', '))}</td><td>${durationText(durationMinutes(e))}</td></tr>`).join('')}</tbody></table><h3>Participación por funcionario</h3><ul>${Object.entries(people).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<li>${esc(n)}: ${c} evento(s)</li>`).join('')}</ul>`}
function renderReport(){const ev=reportEvents();$('#reportPreview').classList.remove('empty');$('#reportPreview').innerHTML=ev.length?reportHtml(ev):'<div class="empty">No hay eventos para el periodo seleccionado.</div>'}
function printReport(){const ev=reportEvents();printHtml('Informe de eventos',reportHtml(ev))}
function exportReport(type){const ev=reportEvents();const rows=[['Evento','Tipo','Fecha inicio','Fecha término','Lugar','Estado','Equipo','Móviles','Duración minutos','Creado por','Actualizado por'],...ev.map(e=>[e.name,e.type==='Otro'?e.otherType:e.type,e.startDate,e.endDate,e.location,e.status,(e.team||[]).map(p=>`${p.name} (${p.role})`).join('; '),(e.vehicles||[]).map(v=>v.type==='Otro'?v.other:v.type).join('; '),durationMinutes(e),e.createdBy,e.updatedBy])];if(type==='csv'){const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');downloadBlob(csv,`Informe_Eventos_${new Date().getFullYear()}.csv`,'text/csv;charset=utf-8')}else{const table='<table>'+rows.map((r,i)=>`<tr>${r.map(v=>`<${i?'td':'th'}>${esc(v)}</${i?'td':'th'}>`).join('')}</tr>`).join('')+'</table>';downloadBlob('\ufeff'+table,`Informe_Eventos_${new Date().getFullYear()}.xls`,'application/vnd.ms-excel')}}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function backupJson(){downloadBlob(JSON.stringify({version:1,exportedAt:new Date().toISOString(),events:state.events},null,2),`Respaldo_Eventos_${new Date().toISOString().slice(0,10)}.json`,'application/json')}
async function importJson(ev){if(!isAdmin()){toast('Solo un administrador puede importar respaldos');ev.target.value='';return}const file=ev.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!data||!Array.isArray(data.events))throw new Error('Formato inválido');if(!confirm(`El respaldo contiene ${data.events.length} eventos. Esto reemplazará la información existente. ¿Continuar?`))return;await EventStore.replaceAll(data.events);toast('Respaldo importado')}catch(e){console.error(e);toast('El archivo JSON no es válido')}finally{ev.target.value=''}}

document.addEventListener('DOMContentLoaded',setup);
})();
