(()=>{
'use strict';
const { getAllEvents, saveEvent, deleteEventPermanently, replaceAllEvents } = window.RescueDB;

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const state = { events: [], user: '', dashboardDate: new Date(), calendarDate: new Date(), deferredInstall: null, reportEvents: [] };
const statusClass = s => s.toLowerCase().replaceAll(' ','-').replace('á','a');
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nowISO = () => new Date().toISOString();
const fmtDate = d => d ? new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${d}T12:00:00`)) : '—';
const fmtDateTime = d => d ? new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(d)) : '—';
const monthLabel = d => new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric'}).format(d).replace(/^./,x=>x.toUpperCase());
const activeEvents = () => state.events.filter(e=>!e.deleted);
const byId = id => state.events.find(e=>e.id===id);

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function setView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const titles={dashboard:['Dashboard','Resumen operativo del mes actual'],calendar:['Calendario','Vista mensual de coberturas'],events:['Eventos','Gestión y consulta de eventos'],reports:['Informes','Consolidación y exportación'],trash:['Papelera','Eventos eliminados recuperables']};$('#pageTitle').textContent=titles[name][0];$('#pageSubtitle').textContent=titles[name][1];$('#sidebar').classList.remove('open');if(name==='dashboard')renderDashboard();if(name==='calendar')renderCalendar();if(name==='events')renderEvents();if(name==='reports')previewReport();if(name==='trash')renderTrash()}
function badge(status){return `<span class="badge ${statusClass(status)}">${esc(status)}</span>`}
function eventRange(e){return e.startDate===e.endDate?fmtDate(e.startDate):`${fmtDate(e.startDate)} al ${fmtDate(e.endDate)}`}
function eventStart(e){return new Date(`${e.startDate}T${e.presentationTime||'00:00'}:00`)}
function eventEnd(e){return new Date(`${e.endDate}T${e.returnTime||'23:59'}:00`)}
function durationMinutes(e){const m=(eventEnd(e)-eventStart(e))/60000;return Number.isFinite(m)&&m>0?Math.round(m):0}
function durationText(min){return `${Math.floor(min/60)} h ${String(min%60).padStart(2,'0')} min`}
function overlap(a,b){return eventStart(a)<eventEnd(b)&&eventEnd(a)>eventStart(b)}
function vehicleName(v){return v.type==='Otro'?(v.other||'Otro'):v.type}
function typeName(e){return e.type==='Otro'?(e.otherType||'Otro'):e.type}

function calculateWarnings(event, excludeId=null){const warnings=[];const start=eventStart(event),end=eventEnd(event);if(event.endDate<event.startDate)warnings.push('La fecha de término es anterior a la fecha de inicio.');if(end<=start)warnings.push('La llegada estimada a la clínica debe ser posterior a la presentación.');if(!event.members.length)warnings.push('El evento no tiene equipo asignado.');if(!event.vehicles.length)warnings.push('El evento no tiene móvil asignado.');const others=activeEvents().filter(e=>e.id!==excludeId&&e.status!=='Cancelado');for(const other of others){if(!overlap(event,other))continue;const staff=event.members.map(m=>m.name.trim().toLowerCase()).filter(Boolean).filter(n=>other.members.some(x=>x.name.trim().toLowerCase()===n));if(staff.length)warnings.push(`Conflicto de funcionario con “${other.name}”: ${staff.join(', ')}.`);const vehicles=event.vehicles.map(vehicleName).filter(Boolean).filter(n=>other.vehicles.map(vehicleName).includes(n));if(vehicles.length)warnings.push(`Conflicto de móvil con “${other.name}”: ${vehicles.join(', ')}.`)}return [...new Set(warnings)]}
function dashboardAlerts(events){const today=new Date();today.setHours(0,0,0,0);const five=new Date(today);five.setDate(five.getDate()+5);const alerts=[];events.forEach(e=>{const st=new Date(`${e.startDate}T00:00:00`);if(st>=today&&st<=five)alerts.push({level:'warning',text:`${e.name}: ocurre dentro de cinco días.`});if(st>=today&&st<=five&&e.status==='Programado')alerts.push({level:'warning',text:`${e.name}: próximo y aún no confirmado.`});if(!e.members.length)alerts.push({level:'error',text:`${e.name}: sin equipo asignado.`});if(!e.vehicles.length)alerts.push({level:'error',text:`${e.name}: sin móvil asignado.`});calculateWarnings(e,e.id).filter(x=>x.startsWith('Conflicto')).forEach(text=>alerts.push({level:'warning',text:`${e.name}: ${text}`}))});return alerts}

async function load(){try{state.events=await getAllEvents();}catch(error){console.error(error);state.events=[];toast('No se pudo abrir la base local. La app seguirá disponible, pero revisa los permisos del navegador.');}state.user=localStorage.getItem('rescateUser')||'';if(state.user){$('#sessionUser').value=state.user}renderAll();}
function renderAll(){$('#activeUser').textContent=state.user||'Sin identificar';renderDashboard();renderCalendar();renderEvents();renderTrash();}
function requireUser(){const name=$('#sessionUser').value.trim();if(name.length<4){toast('Ingresa nombre y apellido. La trazabilidad no funciona con “yo”.');return false}state.user=name;localStorage.setItem('rescateUser',name);$('#activeUser').textContent=name;$('#sessionModal').classList.remove('open');return true}

function renderDashboard(){const d=state.dashboardDate,y=d.getFullYear(),m=d.getMonth();$('#dashMonth').textContent=monthLabel(d);const monthEvents=activeEvents().filter(e=>{const dt=new Date(`${e.startDate}T12:00:00`);return dt.getFullYear()===y&&dt.getMonth()===m});const today=new Date();today.setHours(0,0,0,0);const metrics=[['Total de eventos',monthEvents.length],['Próximos',monthEvents.filter(e=>new Date(`${e.startDate}T00:00:00`)>=today&&e.status!=='Cancelado').length],['Confirmados',monthEvents.filter(e=>e.status==='Confirmado').length],['Finalizados',monthEvents.filter(e=>e.status==='Finalizado').length],['Cancelados',monthEvents.filter(e=>e.status==='Cancelado').length],['Horas de cobertura',(monthEvents.reduce((a,e)=>a+durationMinutes(e),0)/60).toFixed(1)]];$('#metricCards').innerHTML=metrics.map(([l,v])=>`<div class="metric-card"><span>${l}</span><strong>${v}</strong></div>`).join('');const upcoming=activeEvents().filter(e=>new Date(`${e.startDate}T00:00:00`)>=today&&e.status!=='Cancelado').sort((a,b)=>eventStart(a)-eventStart(b)).slice(0,8);$('#upcomingList').innerHTML=upcoming.length?upcoming.map(e=>`<div class="list-item"><div><strong>${esc(e.name)}</strong><small>${fmtDate(e.startDate)} · ${esc(e.location)}<br>${e.members.length} integrante(s) · ${e.vehicles.map(vehicleName).join(', ')||'Sin móvil'}</small></div>${badge(e.status)}</div>`).join(''):'<p class="muted">No hay próximos eventos.</p>';const alerts=dashboardAlerts(activeEvents());$('#alertsList').innerHTML=alerts.length?alerts.slice(0,12).map(a=>`<div class="alert ${a.level}">${esc(a.text)}</div>`).join(''):'<p class="muted">Sin alertas activas. Milagrosamente, todo parece en orden.</p>';const staff={};monthEvents.forEach(e=>e.members.forEach(m=>staff[m.name]=(staff[m.name]||0)+1));$('#staffRanking').innerHTML=Object.entries(staff).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([n,c],i)=>`<div class="list-item"><span>${i+1}. ${esc(n)}</span><strong>${c} evento(s)</strong></div>`).join('')||'<p class="muted">Sin participación registrada.</p>';const counts={Deportivo:0,Académico:0,Otro:0};monthEvents.forEach(e=>counts[e.type]=(counts[e.type]||0)+1);$('#typeSummary').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="list-item"><span>${k}</span><strong>${v}</strong></div>`).join('')}

function renderCalendar(){const d=state.calendarDate;$('#calMonth').textContent=monthLabel(d);const y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());const heads=['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'].map(x=>`<div class="cal-head">${x}</div>`).join('');let days='';for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const iso=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`;const events=activeEvents().filter(e=>iso>=e.startDate&&iso<=e.endDate);days+=`<div class="cal-day ${day.getMonth()!==m?'outside':''}"><div class="cal-date">${day.getDate()}</div>${events.map(e=>`<button class="cal-event ${statusClass(e.status)}" data-open="${e.id}">${esc(e.name)}</button>`).join('')}</div>`}$('#calendarGrid').innerHTML=heads+days;$$('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open))}

function filteredEvents(prefix='f'){const text=$(`#${prefix}Text`)?.value.trim().toLowerCase()||'',start=$(`#${prefix}Start`)?.value||'',end=$(`#${prefix}End`)?.value||'',type=$(`#${prefix}Type`)?.value||'',status=$(`#${prefix}Status`)?.value||'',role=$(`#${prefix}Role`)?.value||'',vehicle=$(`#${prefix}Vehicle`)?.value||'',staff=$(`#${prefix}Staff`)?.value.trim().toLowerCase()||'';return activeEvents().filter(e=>{const hay=[e.name,e.location,e.type,e.otherType,e.status,...e.members.map(m=>m.name),...e.vehicles.map(vehicleName)].join(' ').toLowerCase();return(!text||hay.includes(text))&&(!start||e.endDate>=start)&&(!end||e.startDate<=end)&&(!type||e.type===type)&&(!status||e.status===status)&&(!role||e.members.some(m=>m.role===role))&&(!vehicle||e.vehicles.some(v=>v.type===vehicle))&&(!staff||e.members.some(m=>m.name.toLowerCase().includes(staff)))})}
function renderEvents(){const events=filteredEvents('f').sort((a,b)=>eventStart(b)-eventStart(a));$('#eventsTableBody').innerHTML=events.length?events.map(e=>`<tr><td><strong>${esc(e.name)}</strong><br><small>${esc(typeName(e))}</small></td><td>${eventRange(e)}</td><td>${esc(e.location)}</td><td>${badge(e.status)}</td><td>${e.members.map(m=>esc(m.name)).join('<br>')||'<span class="muted">Sin equipo</span>'}</td><td>${e.vehicles.map(v=>esc(vehicleName(v))).join(', ')||'<span class="muted">Sin móvil</span>'}</td><td>${durationText(durationMinutes(e))}</td><td><div class="actions"><button data-action="view" data-id="${e.id}">Ver</button><button data-action="edit" data-id="${e.id}">Editar</button><button data-action="wa" data-id="${e.id}">WhatsApp</button><button data-action="pdf" data-id="${e.id}">PDF</button><button data-action="delete" data-id="${e.id}">Eliminar</button></div></td></tr>`).join(''):'<tr><td colspan="8" class="muted">No hay eventos que coincidan con los filtros.</td></tr>';$$('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action,b.dataset.id))}

function addMember(data={}){const row=document.createElement('div');row.className='member-row';row.innerHTML=`<input class="member-name" placeholder="Nombre completo" value="${esc(data.name||'')}" list="staffSuggestions"><select class="member-role"><option>Enfermero/a</option><option>TENS</option><option>Conductor/a</option><option>Médico/a</option><option>Otro</option></select><select class="member-condition"><option>Interno</option><option>Externo</option></select><select class="member-participation"><option>Titular</option><option>Reemplazo</option></select><button type="button" class="btn danger remove-row">Quitar</button>`;$('.member-role',row).value=data.role||'Enfermero/a';$('.member-condition',row).value=data.condition||'Interno';$('.member-participation',row).value=data.participation||'Titular';$('.remove-row',row).onclick=()=>row.remove();$('#membersContainer').append(row)}
function addVehicle(data={}){const row=document.createElement('div');row.className='vehicle-row';row.innerHTML=`<select class="vehicle-type"><option>M2</option><option>M4</option><option>M5</option><option>VIR</option><option>Otro</option></select><input class="vehicle-other hidden" placeholder="Especificar móvil" value="${esc(data.other||'')}"><button type="button" class="btn danger remove-row">Quitar</button>`;$('.vehicle-type',row).value=data.type||'M5';const toggle=()=>$('.vehicle-other',row).classList.toggle('hidden',$('.vehicle-type',row).value!=='Otro');$('.vehicle-type',row).onchange=toggle;toggle();$('.remove-row',row).onclick=()=>row.remove();$('#vehiclesContainer').append(row)}
function resetForm(){$('#eventForm').reset();$('#eventId').value='';$('#membersContainer').innerHTML='';$('#vehiclesContainer').innerHTML='';$('#otherTypeWrap').classList.add('hidden');$('#cancelReasonWrap').classList.add('hidden');$('#validationSummary').classList.add('hidden');addMember();addVehicle();const today=new Date().toISOString().slice(0,10);$('#startDate').value=today;$('#endDate').value=today;updateDuration()}
function openEventForm(event=null){resetForm();$('#eventModalTitle').textContent=event?'Editar evento':'Nuevo evento';if(event){$('#eventId').value=event.id;$('#eventName').value=event.name;$('#eventType').value=event.type;$('#otherType').value=event.otherType||'';$('#eventLocation').value=event.location;$('#startDate').value=event.startDate;$('#endDate').value=event.endDate;$('#eventStatus').value=event.status;$('#cancelReason').value=event.cancelReason||'';$('#presentationTime').value=event.presentationTime;$('#arrivalTime').value=event.arrivalTime;$('#eventStartTime').value=event.eventStartTime;$('#eventEndTime').value=event.eventEndTime;$('#returnTime').value=event.returnTime;$('#eventNotes').value=event.notes||'';$('#membersContainer').innerHTML='';event.members.forEach(addMember);$('#vehiclesContainer').innerHTML='';event.vehicles.forEach(addVehicle);toggleConditionalFields();updateDuration()}$('#eventModal').classList.add('open')}
function toggleConditionalFields(){$('#otherTypeWrap').classList.toggle('hidden',$('#eventType').value!=='Otro');$('#cancelReasonWrap').classList.toggle('hidden',$('#eventStatus').value!=='Cancelado')}
function updateDuration(){const sd=$('#startDate').value,ed=$('#endDate').value,st=$('#presentationTime').value,et=$('#returnTime').value;if(!sd||!ed||!st||!et){$('#durationPreview').textContent='0 h 00 min';return}const min=Math.round((new Date(`${ed}T${et}`)-new Date(`${sd}T${st}`))/60000);$('#durationPreview').textContent=min>0?durationText(min):'Duración inválida'}
function formData(){return{name:$('#eventName').value.trim(),type:$('#eventType').value,otherType:$('#otherType').value.trim(),location:$('#eventLocation').value.trim(),startDate:$('#startDate').value,endDate:$('#endDate').value,status:$('#eventStatus').value,cancelReason:$('#cancelReason').value.trim(),presentationTime:$('#presentationTime').value,arrivalTime:$('#arrivalTime').value,eventStartTime:$('#eventStartTime').value,eventEndTime:$('#eventEndTime').value,returnTime:$('#returnTime').value,notes:$('#eventNotes').value.trim(),members:$$('.member-row').map(r=>({name:$('.member-name',r).value.trim(),role:$('.member-role',r).value,condition:$('.member-condition',r).value,participation:$('.member-participation',r).value})).filter(m=>m.name),vehicles:$$('.vehicle-row').map(r=>({type:$('.vehicle-type',r).value,other:$('.vehicle-other',r).value.trim()})).filter(v=>v.type!=='Otro'||v.other)}}
function validate(data){const e=[];if(!data.name)e.push('Nombre del evento obligatorio.');if(!data.type)e.push('Tipo obligatorio.');if(data.type==='Otro'&&!data.otherType)e.push('Debe especificar el tipo de evento.');if(!data.location)e.push('Lugar obligatorio.');if(!data.startDate||!data.endDate)e.push('Fechas obligatorias.');if(data.status==='Cancelado'&&!data.cancelReason)e.push('Motivo de cancelación obligatorio.');['presentationTime','arrivalTime','eventStartTime','eventEndTime','returnTime'].forEach(k=>{if(!data[k])e.push('Todos los horarios son obligatorios.')});if(data.endDate<data.startDate)e.push('La fecha de término no puede ser anterior al inicio.');if(eventEnd(data)<=eventStart(data))e.push('La llegada estimada a la clínica debe ser posterior a la presentación.');return [...new Set(e)]}
async function submitEvent(ev){ev.preventDefault();const data=formData(),errors=validate(data),id=$('#eventId').value;if(errors.length){$('#validationSummary').innerHTML=errors.map(x=>`• ${esc(x)}`).join('<br>');$('#validationSummary').classList.remove('hidden');return}const warnings=calculateWarnings(data,id||null);const conflicts=warnings.filter(x=>x.startsWith('Conflicto'));if(conflicts.length&&!confirm(`Se detectó un conflicto de horario:\n\n${conflicts.join('\n')}\n\n¿Desea guardar igualmente?`))return;const old=id?byId(id):null,time=nowISO();const history=old?.history?[...old.history]:[];history.push({at:time,user:state.user,action:old?'Modificación de evento':'Creación de evento',detail:old?describeChanges(old,data):'Evento creado'});const record={...old,...data,id:id||uid(),createdAt:old?.createdAt||time,createdBy:old?.createdBy||state.user,updatedAt:time,updatedBy:state.user,deleted:false,history};await saveEvent(record);state.events=await getAllEvents();$('#eventModal').classList.remove('open');renderAll();toast(old?'Evento actualizado.':'Evento creado.')}
function describeChanges(old,n){const fields={name:'nombre',type:'tipo',location:'lugar',startDate:'fecha inicial',endDate:'fecha final',status:'estado',presentationTime:'presentación',arrivalTime:'llegada al evento',eventStartTime:'inicio',eventEndTime:'término',returnTime:'regreso',notes:'observaciones'};const changed=Object.entries(fields).filter(([k])=>JSON.stringify(old[k])!==JSON.stringify(n[k])).map(([,v])=>v);if(JSON.stringify(old.members)!==JSON.stringify(n.members))changed.push('equipo');if(JSON.stringify(old.vehicles)!==JSON.stringify(n.vehicles))changed.push('móviles');return changed.length?`Campos modificados: ${changed.join(', ')}`:'Guardado sin cambios visibles'}

function openDetail(id){const e=byId(id);if(!e)return;$('#detailContent').innerHTML=`<div class="detail-grid"><div class="detail-card"><strong>Nombre</strong><br>${esc(e.name)}</div><div class="detail-card"><strong>Tipo</strong><br>${esc(typeName(e))}</div><div class="detail-card"><strong>Fecha</strong><br>${eventRange(e)}</div><div class="detail-card"><strong>Lugar</strong><br>${esc(e.location)}</div><div class="detail-card"><strong>Estado</strong><br>${badge(e.status)}</div><div class="detail-card"><strong>Duración</strong><br>${durationText(durationMinutes(e))}</div></div><h3>Horarios</h3><div class="detail-grid"><div class="detail-card">Presentación: ${e.presentationTime}</div><div class="detail-card">Llegada evento: ${e.arrivalTime}</div><div class="detail-card">Inicio: ${e.eventStartTime}</div><div class="detail-card">Término: ${e.eventEndTime}</div><div class="detail-card">Regreso clínica: ${e.returnTime}</div></div><h3>Equipo</h3>${e.members.length?e.members.map(m=>`<div class="list-item"><span><strong>${esc(m.name)}</strong><br><small>${esc(m.role)} · ${esc(m.condition)} · ${esc(m.participation)}</small></span><strong>${durationText(durationMinutes(e))}</strong></div>`).join(''):'<p class="muted">Sin equipo asignado.</p>'}<h3>Móviles</h3><p>${e.vehicles.map(v=>esc(vehicleName(v))).join(', ')||'Sin móvil asignado'}</p>${e.status==='Cancelado'?`<h3>Motivo de cancelación</h3><p>${esc(e.cancelReason)}</p>`:''}<h3>Observaciones</h3><p>${esc(e.notes)||'Sin observaciones'}</p><h3>Trazabilidad</h3><p><strong>Creado por:</strong> ${esc(e.createdBy)} · ${fmtDateTime(e.createdAt)}<br><strong>Última modificación:</strong> ${esc(e.updatedBy)} · ${fmtDateTime(e.updatedAt)}</p>${(e.history||[]).slice().reverse().map(h=>`<div class="history-item"><strong>${esc(h.action)}</strong><br><small>${esc(h.user)} · ${fmtDateTime(h.at)}</small><br>${esc(h.detail)}</div>`).join('')}<div class="modal-actions"><button class="btn ghost" id="detailWa">WhatsApp</button><button class="btn ghost" id="detailPdf">Exportar PDF</button><button class="btn primary" id="detailEdit">Editar</button></div>`;$('#detailWa').onclick=()=>shareWhatsApp(e);$('#detailPdf').onclick=()=>exportEventPDF(e);$('#detailEdit').onclick=()=>{$('#detailModal').classList.remove('open');openEventForm(e)};$('#detailModal').classList.add('open')}
async function handleAction(action,id){const e=byId(id);if(action==='view')openDetail(id);if(action==='edit')openEventForm(e);if(action==='wa')shareWhatsApp(e);if(action==='pdf')exportEventPDF(e);if(action==='delete'){const reason=prompt('Motivo de eliminación:');if(reason===null)return;if(!reason.trim()){toast('El motivo de eliminación es obligatorio.');return}e.deleted=true;e.deletedAt=nowISO();e.deletedBy=state.user;e.deleteReason=reason.trim();e.updatedAt=e.deletedAt;e.updatedBy=state.user;e.history=[...(e.history||[]),{at:e.deletedAt,user:state.user,action:'Eliminación',detail:reason.trim()}];await saveEvent(e);state.events=await getAllEvents();renderAll();toast('Evento enviado a la papelera.')}}
function renderTrash(){const events=state.events.filter(e=>e.deleted);$('#trashTableBody').innerHTML=events.length?events.map(e=>`<tr><td>${esc(e.name)}</td><td>${fmtDateTime(e.deletedAt)}</td><td>${esc(e.deletedBy)}</td><td>${esc(e.deleteReason)}</td><td><div class="actions"><button data-restore="${e.id}">Restaurar</button><button data-purge="${e.id}">Eliminar definitivamente</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="muted">La papelera está vacía.</td></tr>';$$('[data-restore]').forEach(b=>b.onclick=()=>restoreEvent(b.dataset.restore));$$('[data-purge]').forEach(b=>b.onclick=()=>purgeEvent(b.dataset.purge))}
async function restoreEvent(id){const e=byId(id);e.deleted=false;e.restoredAt=nowISO();e.restoredBy=state.user;e.updatedAt=e.restoredAt;e.updatedBy=state.user;e.history=[...(e.history||[]),{at:e.restoredAt,user:state.user,action:'Restauración desde papelera',detail:'Evento restaurado'}];await saveEvent(e);state.events=await getAllEvents();renderAll();toast('Evento restaurado.')}
async function purgeEvent(id){if(!confirm('Esta acción eliminará el evento definitivamente. No habrá botón mágico de arrepentimiento. ¿Continuar?'))return;await deleteEventPermanently(id);state.events=await getAllEvents();renderAll();toast('Evento eliminado definitivamente.')}

function whatsappText(e){return `Cobertura de evento – Rescate CUA\n\nEvento: ${e.name}\nTipo: ${typeName(e)}\nFecha: ${eventRange(e)}\nLugar: ${e.location}\nPresentación en clínica: ${e.presentationTime} horas\nLlegada al evento: ${e.arrivalTime} horas\nInicio: ${e.eventStartTime} horas\nTérmino: ${e.eventEndTime} horas\nLlegada estimada a clínica: ${e.returnTime} horas\n\nEquipo asistente:\n${e.members.map(m=>`• ${m.role}: ${m.name}`).join('\n')||'• Sin equipo asignado'}\n\nMóvil: ${e.vehicles.map(vehicleName).join(', ')||'Sin móvil asignado'}\nEstado: ${e.status}`}
function shareWhatsApp(e){window.open(`https://wa.me/?text=${encodeURIComponent(whatsappText(e))}`,'_blank','noopener')}
function slug(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_|_$/g,'')}
function download(content,name,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function printHTML(title,body){const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;color:#17324a;margin:36px}h1{color:#0b4f8a;border-bottom:3px solid #2d8f63;padding-bottom:10px}h2{margin-top:24px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #ccd8e1;text-align:left;font-size:12px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{padding:10px;background:#f1f6f9;border-radius:6px}@page{size:letter;margin:16mm}</style></head><body>${body}<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}
function exportEventPDF(e){const body=`<h1>Informe individual de evento</h1><div class="meta"><div class="box"><b>Evento:</b> ${esc(e.name)}</div><div class="box"><b>Tipo:</b> ${esc(typeName(e))}</div><div class="box"><b>Fecha:</b> ${eventRange(e)}</div><div class="box"><b>Lugar:</b> ${esc(e.location)}</div><div class="box"><b>Estado:</b> ${esc(e.status)}</div><div class="box"><b>Duración:</b> ${durationText(durationMinutes(e))}</div></div><h2>Horarios</h2><table><tr><th>Presentación</th><th>Llegada</th><th>Inicio</th><th>Término</th><th>Regreso</th></tr><tr><td>${e.presentationTime}</td><td>${e.arrivalTime}</td><td>${e.eventStartTime}</td><td>${e.eventEndTime}</td><td>${e.returnTime}</td></tr></table><h2>Equipo asistente</h2><table><tr><th>Nombre</th><th>Cargo</th><th>Condición</th><th>Participación</th><th>Horas</th></tr>${e.members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.role)}</td><td>${esc(m.condition)}</td><td>${esc(m.participation)}</td><td>${durationText(durationMinutes(e))}</td></tr>`).join('')}</table><h2>Móviles</h2><p>${e.vehicles.map(v=>esc(vehicleName(v))).join(', ')}</p><h2>Observaciones</h2><p>${esc(e.notes)||'Sin observaciones'}</p><p><b>Creado por:</b> ${esc(e.createdBy)}<br><b>Última modificación:</b> ${esc(e.updatedBy)}</p>`;printHTML(`Evento_${slug(e.name)}`,body)}

function reportFilter(){state.reportEvents=filteredEvents('r').sort((a,b)=>eventStart(a)-eventStart(b));return state.reportEvents}
function previewReport(){const events=reportFilter(),totalMin=events.reduce((a,e)=>a+durationMinutes(e),0);const staff={};events.forEach(e=>e.members.forEach(m=>staff[m.name]=(staff[m.name]||0)+1));$('#reportPreview').innerHTML=`<h2>Informe consolidado de eventos</h2><p><strong>Periodo:</strong> ${$('#rStart').value?fmtDate($('#rStart').value):'Sin límite'} al ${$('#rEnd').value?fmtDate($('#rEnd').value):'Sin límite'}</p><div class="report-summary"><div><small>Total</small><strong>${events.length}</strong></div><div><small>Confirmados</small><strong>${events.filter(e=>e.status==='Confirmado').length}</strong></div><div><small>Finalizados</small><strong>${events.filter(e=>e.status==='Finalizado').length}</strong></div><div><small>Cancelados</small><strong>${events.filter(e=>e.status==='Cancelado').length}</strong></div><div><small>Horas</small><strong>${(totalMin/60).toFixed(1)}</strong></div></div><h3>Listado de eventos</h3><div class="table-wrap"><table><thead><tr><th>Evento</th><th>Fecha</th><th>Tipo</th><th>Estado</th><th>Equipo</th><th>Móviles</th><th>Duración</th></tr></thead><tbody>${events.map(e=>`<tr><td>${esc(e.name)}</td><td>${eventRange(e)}</td><td>${esc(typeName(e))}</td><td>${esc(e.status)}</td><td>${e.members.map(m=>esc(m.name)).join(', ')}</td><td>${e.vehicles.map(v=>esc(vehicleName(v))).join(', ')}</td><td>${durationText(durationMinutes(e))}</td></tr>`).join('')}</tbody></table></div><h3>Participación por funcionario</h3>${Object.entries(staff).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="list-item"><span>${esc(n)}</span><strong>${c} evento(s)</strong></div>`).join('')||'<p class="muted">Sin registros.</p>'}`}
function reportFilename(ext){const s=$('#rStart').value,e=$('#rEnd').value;if(s&&e)return `Informe_Eventos_${s.split('-').reverse().join('-')}_al_${e.split('-').reverse().join('-')}.${ext}`;return `Informe_Eventos_${new Date().getFullYear()}.${ext}`}
function exportReportPDF(){previewReport();printHTML('Informe de eventos',$('#reportPreview').innerHTML)}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
function exportReportCSV(){const events=reportFilter();const rows=[['Nombre','Tipo','Fecha inicio','Fecha término','Lugar','Estado','Presentación','Llegada evento','Inicio','Término','Regreso','Duración minutos','Equipo','Móviles','Observaciones'],...events.map(e=>[e.name,typeName(e),e.startDate,e.endDate,e.location,e.status,e.presentationTime,e.arrivalTime,e.eventStartTime,e.eventEndTime,e.returnTime,durationMinutes(e),e.members.map(m=>`${m.name} (${m.role})`).join('; '),e.vehicles.map(vehicleName).join('; '),e.notes])];download('\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\n'),reportFilename('csv'),'text/csv;charset=utf-8')}
function exportReportExcel(){const events=reportFilter();const rows=events.map(e=>`<Row><Cell><Data ss:Type="String">${xml(e.name)}</Data></Cell><Cell><Data ss:Type="String">${xml(typeName(e))}</Data></Cell><Cell><Data ss:Type="String">${e.startDate}</Data></Cell><Cell><Data ss:Type="String">${e.endDate}</Data></Cell><Cell><Data ss:Type="String">${xml(e.location)}</Data></Cell><Cell><Data ss:Type="String">${xml(e.status)}</Data></Cell><Cell><Data ss:Type="Number">${durationMinutes(e)/60}</Data></Cell><Cell><Data ss:Type="String">${xml(e.members.map(m=>`${m.name} (${m.role})`).join('; '))}</Data></Cell><Cell><Data ss:Type="String">${xml(e.vehicles.map(vehicleName).join('; '))}</Data></Cell></Row>`).join('');const doc=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Eventos"><Table><Row><Cell><Data ss:Type="String">Nombre</Data></Cell><Cell><Data ss:Type="String">Tipo</Data></Cell><Cell><Data ss:Type="String">Inicio</Data></Cell><Cell><Data ss:Type="String">Término</Data></Cell><Cell><Data ss:Type="String">Lugar</Data></Cell><Cell><Data ss:Type="String">Estado</Data></Cell><Cell><Data ss:Type="String">Horas</Data></Cell><Cell><Data ss:Type="String">Equipo</Data></Cell><Cell><Data ss:Type="String">Móviles</Data></Cell></Row>${rows}</Table></Worksheet></Workbook>`;download(doc,reportFilename('xls'),'application/vnd.ms-excel')}
function xml(s){return String(s??'').replace(/[<>&'"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]))}
function exportBackup(){download(JSON.stringify({app:'Rescate CUA Eventos',version:1,exportedAt:nowISO(),events:state.events},null,2),`Respaldo_Eventos_${new Date().toISOString().slice(0,10)}.json`,'application/json')}
async function importBackup(file){try{const data=JSON.parse(await file.text());if(!data||!Array.isArray(data.events))throw new Error('Formato inválido');if(!data.events.every(e=>e.id&&e.name&&Array.isArray(e.members)&&Array.isArray(e.vehicles)))throw new Error('El respaldo contiene registros incompletos');if(!confirm(`El archivo contiene ${data.events.length} eventos. ¿Desea reemplazar la información existente?`))return;await replaceAllEvents(data.events);state.events=await getAllEvents();renderAll();toast('Respaldo importado correctamente.')}catch(err){toast(`No se pudo importar: ${err.message}`)}}

function bind(){
  $('#startSessionBtn').onclick=requireUser;$('#changeUserBtn').onclick=()=>$('#sessionModal').classList.add('open');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$$('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#newEventBtn').onclick=()=>openEventForm();$$('.close-modal').forEach(b=>b.onclick=()=>$('#eventModal').classList.remove('open'));$('.close-detail').onclick=()=>$('#detailModal').classList.remove('open');$('#eventType').onchange=toggleConditionalFields;$('#eventStatus').onchange=toggleConditionalFields;['startDate','endDate','presentationTime','returnTime'].forEach(id=>$(`#${id}`).addEventListener('input',updateDuration));$('#addMemberBtn').onclick=()=>addMember();$('#addVehicleBtn').onclick=()=>addVehicle();$('#eventForm').onsubmit=submitEvent;$('#dashPrev').onclick=()=>{state.dashboardDate.setMonth(state.dashboardDate.getMonth()-1);renderDashboard()};$('#dashNext').onclick=()=>{state.dashboardDate.setMonth(state.dashboardDate.getMonth()+1);renderDashboard()};$('#calPrev').onclick=()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()-1);renderCalendar()};$('#calNext').onclick=()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()+1);renderCalendar()};['fText','fStart','fEnd','fType','fStatus','fRole','fVehicle'].forEach(id=>$(`#${id}`).addEventListener('input',renderEvents));$('#clearFiltersBtn').onclick=()=>{['fText','fStart','fEnd','fType','fStatus','fRole','fVehicle'].forEach(id=>$(`#${id}`).value='');renderEvents()};$('#previewReportBtn').onclick=previewReport;$('#exportReportPdfBtn').onclick=exportReportPDF;$('#exportReportExcelBtn').onclick=exportReportExcel;$('#exportReportCsvBtn').onclick=exportReportCSV;$('#backupBtn').onclick=exportBackup;$('#importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$('#installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.error)
}

document.addEventListener('DOMContentLoaded',async()=>{bind();await load();if(!state.user)$('#sessionModal').classList.add('open');else $('#sessionModal').classList.remove('open')});

})();
